### ISSUE TITLE
Unexpected input 'instance_ids', valid inputs are ['instance_id', 'commands', 'document_name', 'working_directory', 'comment']

### ISSUE THREAD

**Issue by lucarducci** [peterkimzz/aws-ssm-send-command#2]
Is instance_id or instance_ids ?

**Comment by peterkimzz** [comment]
Hi, lucarducci.
Thank you for your question.

Actually current version of the action is not stable and has not enough infomation for usage. I'm going to fix in tomorrow.

Thank you!
Peter

**Comment by peterkimzz** [comment]
It is released by 1.0.1 version.
