### ISSUE TITLE
Do you know what could be causing this error?

### ISSUE THREAD

**Issue by howjack** [peterkimzz/aws-ssm-send-command#23]
`InvalidInstanceId: Instances [[***]] not in a valid state for account 28878`

**Comment by SiegeSailor** [comment]
I am also facing this error. I have checked that my `aws ssm agent` and `aws cli` is installed, and I have assigned an IAM role for it.

**Comment by pribadi1st** [comment]
try check your AMI role, it requires `AmazonSSMFullAccess`
