### ISSUE TITLE
InvalidInstanceId: null

### ISSUE THREAD

**Issue by kellym** [peterkimzz/aws-ssm-send-command#4]
No matter how I configure my instance ID, I always get this error from the AWS library.

```
/home/runner/work/_actions/peterkimzz/aws-ssm-send-command/1.0.1/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

InvalidInstanceId: null
```

I've looked through the code and I'm not quite certain why it's not sending my instance ids. It appears it should. Any ideas? I'm on 1.0.1.

**Comment by kellym** [comment]
User error. Resolved. :-) This was misconfigured in AWS.

**Comment by peterkimzz** [comment]
Hi, kellym.

Some users have asked me the same issue with the User Error, but I haven't figured out the exact cause yet. If you resolved the issue, could you please tell me what the problem was?

I'd appreciate your reply. Then I could update the read me file.

**Comment by kellym** [comment]
It was a lack of configuring my machine in AWS to support AWS Systems Manager. Essentially, the instance ID wasn't a valid instance to handle messages.  Once I set up the proper IAM accounts and roles, it worked perfectly.

**Comment by peterkimzz** [comment]
Very helpful, thank you. :)
